---

- name: Apt-get update before installing
  apt: update_cache=yes


- name: Install HAproxy  & socat debian
  apt: pkg={{ item }} state=present
  with_items:
    - socat    
    - haproxy

- stat: path=/etc/default/haproxy
  register: default_file

- name: Enable init script
  when: default_file.stat.exists
  replace: dest='/etc/default/haproxy' 
         regexp='ENABLED=0'
         replace='ENABLED=1'

